package com.syan.netonej.http.entity.ca;

import com.syan.netonej.common.dict.ResponseFormat;
import com.syan.netonej.common.json.JSONException;
import com.syan.netonej.common.json.JSONObject;
import com.syan.netonej.exception.NetonejException;
import com.syan.netonej.http.entity.NetoneResponse;


public class CertificateResponse extends NetoneResponse {
    private String signatureCert;

    private String encryptionCert;

    private String encryptionKey;

    public CertificateResponse(NetoneResponse response) throws NetonejException {
        super(response.getStatusCode());
        if(response != null && response.getStatusCode() == 200){
            String result = response.getResult();
            if(response.getFormat() == ResponseFormat.TEXT){
                try {
                    //result示例值：
                    //{"signatureCert":"MIIDwjCCAqqgAwIBAgINANoYhEJfJKGMqjwWWzANBgkqhkiG9w0BAQsFADAiMQswCQYDVQQGEwJDTjETMBEGA1UEAwwKcnNhMjA0OF9jYTAeFw0yNTA5MDIwNjA2MjdaFw0yNTEwMDIwNjA2MjdaMBwxCzAJBgNVBAYTAkNOMQ0wCwYDVQQDDAR4dXl5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1NSWWS5WiBZAtHAV+oSLzn3xZdLj1Tdn3MAz6bmskkOPY3HW7Di2lvg2QDF+Q2yhKQEqANGZktOLUT/CY/6O6ERdFXG+Z4HSCdJHw/laP71tXOwu5hbyq1eCrB8oWSce3i0VsyFiHUM0Vi18+OucMa8mHK6BLETVVxulQ9iaFewR289NjWZ0ttVSHh1gKwBLvFvWnEnmOl1Mbqrie5FYdpu8ZWhyCVjdzrUPidUrUkSExfo+tIcW61oF/PP/yHOYZweoFSluPZBBZEa/tf1Da7X7kbPKcCwfNK314D72FfU1ytDkyFM5OTqPY0c3bfykzlXH+xfwUiWnYVXZALOtgQIDAQABo4H8MIH5MAkGA1UdEwQCMAAwHQYDVR0OBBYEFLDpyMIeM+tfjKtduUF7SVKPYjp+MA4GA1UdDwEB/wQEAwIGwDCBmwYDVR0lAQH/BIGQMIGNBggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCisGAQQBgjcCARUGCisGAQQBgjcCARYGCisGAQQBgjcKAwEGCisGAQQBgjcKAwMGCisGAQQBgjcKAwQGCWCGSAGG+EIEAQYIKwYBBQUHAwkGCCsGAQUFBwMKMB8GA1UdIwQYMBaAFCPIN38X9W3ARAGlLAQCPeRIxa6GMA0GCSqGSIb3DQEBCwUAA4IBAQAJdzAB//mo3dj9xjAtzrBjyv3or7axdm18JpQUE+1RGKU/OAftZZQqGGnv9DHxUfWxrj87EG0w4l2YJJDP/ypPDKPRq9Sc+9kgTteFIQ9Uf8YCX1jblWv1bVb6GM5sR1jJWXs+PQxFTHox3kRvbyeZi0p66wggQV6qveJf5DDnInycXsK4o0ODI6mBJaf8UVjAJOVMskoy9+cm63APUS/JF85C1GtJ5AZV/FetPYdf8OFjgFN30+gSCnQscm+AJs3gLxWoy+CW+F3qowm29d10iZ4+b3YQoxVzEnpQjJdvFPZCA7MWR8NmrL+lYPur5/Qt4XHrTalsRUDX0bhw2Blq",
                    // "encryptionCert":"MIIDwjCCAqqgAwIBAgINAOuRv7ErE8jifJaSYjANBgkqhkiG9w0BAQsFADAiMQswCQYDVQQGEwJDTjETMBEGA1UEAwwKcnNhMjA0OF9jYTAeFw0yNTA5MDIwNjA2MjdaFw0yNTEwMDIwNjA2MjdaMBwxCzAJBgNVBAYTAkNOMQ0wCwYDVQQDDAR4dXl5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx0nlQh7CK7d/PaEMoKMSY5r6eqzzRpugVptapLvq9rYmQ6PcsN5YCBbjCOD1gOBiOTutU1fw+7vBx3Eb/jKrnY7jDJSWpEk+47O8n7C7/+W0DvNCrXrJFBEjIyeSXScEGaKMTuBgKfnKigUKbGCrNwrmaZ3q9D7GiUlSlA9ov68iKSHfhfMebtSX9RnotcD1Y9dxAas4mdVBwErh7n0oFnq1EnpWDJglGlIXkhCJ9rjlhkA6LUhd64AXQ42le2UuzVB76RYsD59FoR7Rf87jSG5q64nkUvLCDy/s5W23nu0Zc9spzT0vQ+kf3CtH17PiYGm5t+i7UqtoupdN0Ay7CwIDAQABo4H8MIH5MAkGA1UdEwQCMAAwHQYDVR0OBBYEFOiqlhagw6VM46xiJIeIKcmkycNAMA4GA1UdDwEB/wQEAwIDODCBmwYDVR0lAQH/BIGQMIGNBggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCisGAQQBgjcCARUGCisGAQQBgjcCARYGCisGAQQBgjcKAwEGCisGAQQBgjcKAwMGCisGAQQBgjcKAwQGCWCGSAGG+EIEAQYIKwYBBQUHAwkGCCsGAQUFBwMKMB8GA1UdIwQYMBaAFCPIN38X9W3ARAGlLAQCPeRIxa6GMA0GCSqGSIb3DQEBCwUAA4IBAQAo3fkFq9DtxAYQYZ+JdaMTr353VOpXBfVUfzrohVRnNNRK600HtvKq5+nVPHdAO7GvsKW9kzeVVqLL3DU4Ph4a9ZZnlYQxEHCH3jfRar5Rcgs8CwkK4yLbveEuOVkMSWQFY5/4oLqR3F1iuZFys1M2Ga+67r13k9KS+m7Puhx8UPedPMCai8Z4GaN5qqBl47jahukxDSgKESvVnwZTYUb7g5x7kgc37msNLO2NAfDtpBmAOAq5cFXrl6Ma4P39afz20ssSO6wYN83vL/1fkHri7K7v1PNAY+BVyy7lnxrrQnTsco/ejm8xAblBK7n7j/sTkLnIGzHwRhV7U/2G3aIP",
                    // "encryptionKey":"AQQAAAABAABMhwkxpdmZuLcjvhrpd2xrB9DGVoWyVMyVWizQbd5qYmxHoDSpPd3Y1cKtj/dS8TRlNB+aC24mvKQKHnFGQLfPStqKxfuzem+p0shfc3pIL1CwBBg0G1OJhKggjbwb8Kqf4kdsDr2/QGEXT/M+osUFQ+TB/lmmLjtjsi4AWSqZwEjcPMVAfKllbs50z435jTi+1IVJRdktJeRRwgw4WBLCZxBaq4R0WtoVTZ9996MBtSnJbXVol1HzyhuGErs+5d/PLiu+CdN77WMWXHjIGT2co5DDG1jg808mrk2RkpPWWvL8mI+sTJd/BJiuj4jeO6nrSfN0N1UFhh8xkuHt4QzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAQAAONpFaCbPPau04381yAus+NIxIxjFixYP+Nq5b7sZj4ig215pYE2vzWJu1LgE6KjesqQ0791f8Xbwon0rABcvsoMOoxE/QDhyRhdNZAY5c6xwrj0EjDu1NHCeis/jnxArv+bC0zT4pZPk4ixZwJNt2x6GYk1KhIifO3GPHjcLfAv3LbquRAdAiU6KG+ADQ6+xJNAL2fZHiz2T4iNzWHzVFNen4E50b5HgyLjNswXjfeLtV8zHy85Wk72sjLYIdv41lIrgN22jS4xMPi8NdNkmug8vcQ9RcAqeBnEo9L/qqvZt9EoYvQdBaqMbw+Mmi4BckVB5H9NSZFubVC9hOsbZTEGwy6cAssN0GhPKNK9sds79snkDCSiW3uUgiLNirqKbxYkZDcLqN5EX26pcVA1A2fnK6Fyl9Bo1oY9d5vE0/Fd/Oqbf7NRvy8AX7S8AklNvBw7/UbV5DdLnodVxB8QW0vX0QMJk4qmMnkTcc9/kK3O0UjoR6baTLZSxst1rIwbTHibg5q+GilNGsIS4TIS0zN/Ei0b9XZUy08UWZsSLqnDD/6wnWdUwR+qDoTKybffuhtuzKYNFPcICaXb41Anq+Dwr9lx6wdGYYzJuMXNxJU/0F0nnV2V399ypCY5dIDDq3LOdrOrSZitkEF7qjlnQKL8SVF6VyFXQLM/N9u/MoZmEwJfhg9ut/iJdX4JiTgy5+zSkoj9Ro9s4eoPasXmTBlivpsV+gCsbRat964SIjVZe4W2tGpTIlYdJtRCyskJMvud3JO6wmGT3VOhnI6v5lmEjDMlDD8skZi6qNQbFehHAtr/PWr2xcZtykPne90JC3IJwGrIX+H6Rk9UsNP5UDTHFED4YaMj86rbI9IEF4JFU6Xy4EodJEdfQL+YjgLxZRKLS+La1ZCY06PFYKOrqTl+KeQUQOPgWj5MeAA3/jZn6Mv2r342pwJAl7mEHYrw4dbi7pz/XzaVkvTehlogLpUUuqzxr1qZ3Pawl8/Nt3/o/9eipgdXiAjiQGWAxz+nyNfHddBxz+FGfiAcdC0PBUaAL2WcFE+LYQ+6LclG2McpgEx1afmfepwwNXDyIjo7pPWzx4KHO8Npz1ETARnfvGm09BRkYJt22gi3tpbevMiow421edAo5itb9usanXx72Y92+mVM3FHLtZUsI+uKf88dA09I8sjeukMh5RtVOssLFEAg52W0ySx2OXbVPoLd3Kq6KB9nqmxI4/CaCTtAejqzashOt8VycKd1xJSSDpZwzNK/5TvmaV3Gib13OsuFjQ+uWcbVRv/gbXsLtHQvcZ+8zPwtS46tD7b25MMr46d85oaguiTn3p7eATOj47ufjLm/PniQQugjIQcw5H21DE6BpmJpXPr5uqzhlMTkgUXxr9MGGTy6Fsds/qImrFxFO1BUYy/XiYFQJqT/bI7hh529zzTvxg45jujdxCRxfTIJSAaztC5Z83x8E3QuBVW5dDGuIMmLrtCyDOeDIhuMTjWb2GuYCq3tYUUnT6lcKtq7R6r7/rZYO0h7Ef0iLg3lEugvd0t7qe9CqYVWJt9PMZJI1zR6foSG4srb0fO3buAbOY1iC+b0G9gag+d6tS0hyAAAAA=="}
                    JSONObject json = new JSONObject(result);
                    this.setSignatureCert(json.getString("signatureCert")); // 使用optString避免JSONException;
                    this.setEncryptionCert(json.getString("encryptionCert"));
                    this.setEncryptionKey(json.optString("encryptionKey", null));
                } catch (JSONException e) {
                    throw new RuntimeException(e);
                }
            }
        }
    }

    public String getSignatureCert() {
        return signatureCert;
    }

    public void setSignatureCert(String signatureCert) {
        this.signatureCert = signatureCert;
    }

    public String getEncryptionCert() {
        return encryptionCert;
    }

    public void setEncryptionCert(String encryptionCert) {
        this.encryptionCert = encryptionCert;
    }

    public String getEncryptionKey() {
        return encryptionKey;
    }

    public void setEncryptionKey(String encryptionKey) {
        this.encryptionKey = encryptionKey;
    }
}
